dist: trusty
sudo: false
language: node_js
git:
  depth: 5

node_js: stable

cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn build
  - yarn lint
  - yarn test_coverage

after_success: npx codecov
