dist: trusty
sudo: false
language: node_js
git:
  depth: 5

node_js: stable
addons:
  apt:
    - hugo

cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - hugo version

install:
  - yarn
script:
  - yarn build
  - yarn lint

after_success: npx codecov
- touch out/.nojekyll

before_deploy:
- |
  git config user.name "Deployment Bot (from Travis CI)" &&
  git config user.email "deploy@travis-ci.org" &&
  mkdir -p out/$TRAVIS_BRANCH/docs &&
  mv docs/public/* out/$TRAVIS_BRANCH/docs &&
  mkdir -p out/$TRAVIS_BRANCH/@design.beta.gouv/core &&
  mv packages/core/dist out/$TRAVIS_BRANCH/@design.beta.gouv/core/dist
  mv packages/core/fonts out/$TRAVIS_BRANCH/@design.beta.gouv/core/fonts
  mv packages/core/LICENSE out/$TRAVIS_BRANCH/@design.beta.gouv/core/LICENSE
  mv packages/core/package.json out/$TRAVIS_BRANCH/@design.beta.gouv/core/package.json
deploy:
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: out
  provider: pages
  skip_cleanup: true
  target-branch: gh-pages
  on:
    branch: master
