dist: xenial
language: minimal
git:
  depth: 5

addons:
  snaps:
    - name: node
      classic: true
      channel: 10/stable
    - name: ruby
      classic: true
      channel: 2.5/stable

cache:
  directories:
    - $HOME/.cache/yarn
    - $HOME/.bundle
    - $HOME/.gem
    - $TRAVIS_BUILD_DIR/docs/.bundle
    - $TRAVIS_BUILD_DIR/docs/vendor

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --frozen-lockfile
  - cd docs
  - gem install bundler
  - BUNDLE_FROZEN=true bundle install --jobs=3 --retry=3
  - cd ..

script:
  - yarn build --ignore docs
  - yarn lint
  - yarn test
  - cd docs
  - yarn nps build.rollup "build.jekyll --baseurl /design/master/docs"
  - cd ..

before_deploy:
  - |
    git config user.name "Deployment Bot (from Travis CI)" &&
    git config user.email "deploy@travis-ci.org" &&
    mkdir -p out/$TRAVIS_BRANCH/docs &&
    mv docs/_site/* out/$TRAVIS_BRANCH/docs &&
    mkdir -p out/$TRAVIS_BRANCH/@design.beta.gouv/core &&
    mv packages/core/dist out/$TRAVIS_BRANCH/@design.beta.gouv/core/dist &&
    mv packages/core/fonts out/$TRAVIS_BRANCH/@design.beta.gouv/core/fonts &&
    mv packages/core/LICENSE out/$TRAVIS_BRANCH/@design.beta.gouv/core/LICENSE &&
    mv packages/core/package.json out/$TRAVIS_BRANCH/@design.beta.gouv/core/package.json

deploy:
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: out
  provider: pages
  skip_cleanup: true
  target-branch: gh-pages
  on:
    branch: master
