name = "Design Beta Gouv"
license = "APACHE-2.0"
licenselink = "https://github.com/xxxxx/design/blob/master/docs/themes/design-beta-gouv/LICENSE"
description = "Design Beta Gouv Hugo Theme "
homepage = "https://github.com/xxxxx/design"
min_version = "0.41"

[author]
  name = "Design Beta Gouv Team"
  homepage = "https://github.com/xxxxx"

