title: Design Beta Gouv
email: xxxxxx@beta.gouv.fr
description: >-
  The Design Beta Gouv Website
url:
baseurl:
twitter_username: betagouv
github_username: betagouv

# Build settings
markdown: kramdown
highlighter: rouge
theme: design.beta.gouv
permalink: /:categories/:title/
plugins:
  - jekyll-autoprefixer
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - themes
  - package.json
  - package-scripts.yml

sass:
  load_paths:
    - node_modules
    - ../packages
    - ../node_modules
  style: compressed

#
# jekyll-toc options
#

toc:
  min_level: 2
  max_level: 4
  no_toc_section_class:
    - "dbg-docs-callout"
    - "dbg-docs-example"

#
# Custom variables
#

version: master
bootstrap_doc_baseurl: https://getbootstrap.com/docs/4.2
