languageCode = "fr-fr"

title = "Design Beta Gouv"
author = "Design Beta Gouv Team"

theme = "design-beta-gouv"
sectionPagesMenu = "main"

[params]
  description = "Design Beta Gouv"
  version = "master"

  [params.cdn]
    baseURL = "../@design.beta.gouv/core"
