source "https://rubygems.org"

gem "jekyll", "~> 3.8.5"

# Use a local theme
gem 'design.beta.gouv', :path => 'themes'

group :jekyll_plugins do
  gem 'jekyll-autoprefixer', '~> 1.0.1'
  gem 'jekyll-redirect-from', '~> 0.14.0'
  gem 'jekyll-sitemap', '~> 1.2.0'
  gem 'jekyll-toc', '~> 0.9.1'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.0" if Gem.win_platform?

